name: create comment on PR


on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      pr_repo:
        description: 'The repo with the PR.'
        default: 'micropython/micropython'
        required: true
        type: string

      pr_number:
        description: 'Number of the PR to be tested. If != '': Will add a report-comment to the PR.'
        default: '17782'
        required: true
        type: string

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub Context
      # https://manski.net/articles/github/actions/dump-context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT" | jq -C

    - name: Dump GitHub Context 2
      # https://youtu.be/-hVG9z0fCac?si=dAAVltMAbmwyMQBu
      run: echo '${{ toJson(github) }}' | jq -C
      shell: bash

    - name: Dump GitHub Event
      # https://youtu.be/-hVG9z0fCac?si=dAAVltMAbmwyMQBu
      run: echo '${{ toJson(github.event) }}' | jq -C
      shell: bash

    - name: Dump local environment
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: env
      shell: bash

    - name: Determine PR comment authorization
      if: always() && inputs.pr_number != '' && inputs.pr_repo != ''
      run: |
        if [[ "${{ inputs.pr_repo }}" == "${{ github.repository }}" ]]; then
          echo "Simple: Same repo: ${{ inputs.pr_repo }} ${{ github.repository }}"
        elif [[ -n "${{ secrets.OCTOPROBEBOT_GITHUB_TOKEN }}" ]]; then
          echo "Complex: Repos differ and secrets.OCTOPROBEBOT_GITHUB_TOKEN defined"
        else
          echo "Impossible: Repos differ and secrets.OCTOPROBEBOT_GITHUB_TOKEN not defined"
        fi

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v5
      with:
        token: ${{ secrets.OCTOPROBEBOT_GITHUB_TOKEN || github.token }}
        repository: ${{ inputs.pr_repo }}
        issue-number: ${{ inputs.pr_number }}
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:
          - Created by [create-or-update-comment][1]

          [1]: https://github.com/peter-evans/create-or-update-comment
        reactions: '+1'

    - name: Find Comment
      uses: peter-evans/find-comment@v4
      id: findcommend_id
      with:
        token: ${{ secrets.OCTOPROBEBOT_GITHUB_TOKEN || github.token }}
        repository: ${{ inputs.pr_repo }}
        issue-number: ${{ inputs.pr_number }}
        comment-author: 'github-actions[bot]'
        body-includes: '<!-- octoprobe-pr-report:'

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v5
      with:
        token: ${{ secrets.OCTOPROBEBOT_GITHUB_TOKEN || github.token }}
        comment-id: ${{ steps.findcommend_id.outputs.comment-id }}
        repository: ${{ inputs.pr_repo }}
        issue-number: ${{ inputs.pr_number }}
        body: |
          Build output
          <!-- octoprobe-pr-report: xyz -->
          ...
        edit-mode: replace