name: Ruff, Mypy and Pytest

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13.1"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: |
          uv sync --python ${{ matrix.python-version }}
      
      - name: Build docs
        run: |
          make -C docs/ html
          continue-on-error: true

      - name: Ruff
        run: |
          uv run ruff check --output-format github --config pyproject.toml --fix
        continue-on-error: true

      - name: Mypy
        run: |
          uv run mypy --config-file pyproject.toml src tests
        continue-on-error: true

      - name: Test with pytest
        run: |
          uv run pytest tests
        continue-on-error: true
      